include:
  - ./kafka-compose/kraft-1-node.yml
  # - ./kafka-compose/kraft-3-nodes.yml
  # - ./kafka-compose/kraft-3-controllers-3-brokers.yml

services:
  spring-service:
    build: ./spring-service
    container_name: spring-service
    ports:
      - 8080:8080

  # Convenient UI for managing the kafka service
  kafka-ui:
    container_name: kafka-ui
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - 9090:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-01:9093
    depends_on:
      - kafka-01