# See ./kraft-1-node.yml for more detailed comments

# In this setup, all nodes will be both controllers and brokers
services:
  kafka-01:
    image: apache/kafka:latest
    container_name: kafka-01
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: EXTERNAL://:9092, DOCKER://kafka-01:9093, CONTROLLER://kafka-01:9091
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092, DOCKER://kafka-01:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT, DOCKER:PLAINTEXT, CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      KAFKA_NODE_ID: 1
      CLUSTER_ID: EYunGpaGT4u1iThtQKjVQA
      KAFKA_PROCESS_ROLES: broker, controller

      # All nodes will be controllers in the raft quorum
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-01:9091, 2@kafka-02:9091, 3@kafka-03:9091

  kafka-02:
    image: apache/kafka:latest
    container_name: kafka-02
    environment:
      # Same as for kafka-01, except we use kafka-02 as network address
      KAFKA_LISTENERS: EXTERNAL://:9092, DOCKER://kafka-02:9093, CONTROLLER://kafka-02:9091
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092, DOCKER://kafka-02:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT, DOCKER:PLAINTEXT, CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      KAFKA_NODE_ID: 2
      CLUSTER_ID: EYunGpaGT4u1iThtQKjVQA
      KAFKA_PROCESS_ROLES: broker, controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-01:9091, 2@kafka-02:9091, 3@kafka-03:9091
  
  kafka-03:
    image: apache/kafka:latest
    container_name: kafka-03
    environment:
      # Same as for kafka-01, except we use kafka-03 as network address
      KAFKA_LISTENERS: EXTERNAL://:9092, DOCKER://kafka-03:9093, CONTROLLER://kafka-03:9091
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:9092, DOCKER://kafka-03:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT, DOCKER:PLAINTEXT, CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      KAFKA_NODE_ID: 3
      CLUSTER_ID: EYunGpaGT4u1iThtQKjVQA
      KAFKA_PROCESS_ROLES: broker, controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-01:9091, 2@kafka-02:9091, 3@kafka-03:9091